spring:
  datasource:
    db1:
      url: jdbc:mysql://localhost:3306/nanwang
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    db2:
      url: jdbc:mysql://localhost:3306/aaa
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false

logging:
  file:
    path: F:\南网\log
  level:
    root: info

zip-directory:
  weatherDataPath: F:\南网\eFile\eFile-real-power\data\weather
  zipPath: F:\南网\eFile\eFile-real-power\data
  dirPath: F:\南网\eFile\eFile-real-power\files
  list:
    - gd
#    - guiz
#    - gx
#    - hn
#    - yn