spring:
  datasource:
    db1:
      url: jdbc:mysql://11.14.34.162:3306/nanwang
      username: dky
      password: dky100200
      driver-class-name: com.mysql.jdbc.Driver
    db2:
      url: jdbc:mysql://11.14.34.162:3306/xnysf_fzx
      username: dky
      password: dky100200
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false

logging:
  file:
    path: /home/dky/neoda/log/real_power
  level:
    root: info

zip-directory:
  weatherDataPath: /home/dky/data/weather
  zipPath: /home/dky/data
  dirPath: /home/dky/neoda/realPowerFiles
  list:
    - gd
    - guiz
    - gx
    - hn
    - yn